#!/usr/bin/env python3
"""
build_lists.py - regenerate the reference name lists that poke_ocr snaps to,
straight from PokeMMO's dex dump (../dump/*.json).

Run this once, and again whenever the dump is refreshed:
    python build_lists.py

Writes to the data/ folder: moves.txt, abilities.txt, items.txt, species.txt,
species_stats.json (base stats, for the EV-fix suggestions).
"""

import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
DUMP = os.path.join(HERE, "..", "dump")
DATA = os.path.join(HERE, "data")


def _load(name):
    with open(os.path.join(DUMP, name), encoding="utf-8") as fh:
        return json.load(fh)


def _write(fname, names, source):
    names = sorted({n.strip() for n in names
                    if n and n.strip() and not re.fullmatch(r"[-?]+", n.strip())})
    path = os.path.join(DATA, fname)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f"# Auto-generated by build_lists.py from {source}. Do not edit by hand.\n")
        fh.write("\n".join(names) + "\n")
    print(f"  {fname:15} {len(names):5} names")


def main():
    if not os.path.isdir(DUMP):
        raise SystemExit(f"dump folder not found: {DUMP}")
    os.makedirs(DATA, exist_ok=True)

    _write("moves.txt", (s["name"] for s in _load("skills.json")), "dump/skills.json")
    _write("items.txt", (i["name"] for i in _load("items.json")), "dump/items.json")

    monsters = _load("monsters.json")
    real = [m for m in monsters if m.get("obtainable")]  # skip event raid bosses
    _write("abilities.txt",
           (a["name"] for m in real for a in m.get("abilities", [])
            if ":" not in a["name"]),  # ...and their "Config:"/"Task:" mechanics
           "dump/monsters.json")
    _write("species.txt",
           ([m["name"] for m in real]
            + [f["name"] for m in real for f in m.get("forms", [])]),
           "dump/monsters.json")

    stats = {m["name"]: [m["stats"][k] for k in
                         ("hp", "attack", "defense", "sp_attack", "sp_defense", "speed")]
             for m in real if m.get("stats")}
    with open(os.path.join(DATA, "species_stats.json"), "w", encoding="utf-8") as fh:
        json.dump(stats, fh, separators=(",", ":"), sort_keys=True)
    print(f"  {'species_stats.json':15} {len(stats):5} entries")


if __name__ == "__main__":
    print("building reference lists from", os.path.normpath(DUMP))
    main()
