#!/usr/bin/env python3
"""
build_lists.py - regenerate the reference name lists that screenshot.py snaps to,
straight from PokeMMO's dex dump (../dump/*.json).

Run this once, and again whenever the dump is refreshed:
    python build_lists.py

Writes to the data/ folder: moves.txt, abilities.txt, items.txt, species.txt,
species_stats.json (base stats, for the EV-fix suggestions).
"""

import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
DUMP = os.path.join(HERE, "..", "dump")
DATA = os.path.join(HERE, "data")


def _load(name):
    with open(os.path.join(DUMP, name), encoding="utf-8") as fh:
        return json.load(fh)


def _write(fname, names, source):
    names = sorted({n.strip() for n in names
                    if n and n.strip() and not re.fullmatch(r"[-?]+", n.strip())})
    path = os.path.join(DATA, fname)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f"# Auto-generated by build_lists.py from {source}. Do not edit by hand.\n")
        fh.write("\n".join(names) + "\n")
    print(f"  {fname:15} {len(names):5} names")


def main():
    if not os.path.isdir(DUMP):
        raise SystemExit(f"dump folder not found: {DUMP}")
    os.makedirs(DATA, exist_ok=True)

    _write("moves.txt", (s["name"] for s in _load("skills.json")), "dump/skills.json")
    _write("items.txt", (i["name"] for i in _load("items.json")), "dump/items.json")

    monsters = _load("monsters.json")
    real = [m for m in monsters if m.get("obtainable")]  # skip event raid bosses
    _write("abilities.txt",
           (a["name"] for m in real for a in m.get("abilities", [])
            if ":" not in a["name"]),  # ...and their "Config:"/"Task:" mechanics
           "dump/monsters.json")
    _write("species.txt",
           ([m["name"] for m in real]
            + [f["name"] for m in real for f in m.get("forms", [])]),
           "dump/monsters.json")
    # species whose IVs can't come from breeding (legendaries, babies) - PokeMMO
    # lets you re-roll a legendary's IVs, so "wrong breed" isn't the right advice.
    _write("no_breed.txt",
           (m["name"] for m in real if m.get("egg_groups") == ["cannot breed"]),
           "dump/monsters.json")

    stats = {m["name"]: [m["stats"][k] for k in
                         ("hp", "attack", "defense", "sp_attack", "sp_defense", "speed")]
             for m in real if m.get("stats")}
    with open(os.path.join(DATA, "species_stats.json"), "w", encoding="utf-8") as fh:
        json.dump(stats, fh, separators=(",", ":"), sort_keys=True)
    print(f"  {'species_stats.json':15} {len(stats):5} entries")

    # evolution graph: {from_species: [{to, type, val, item}, ...]} - lets the
    # validator tell an under-levelled pre-evo to evolve instead of "wrong mon".
    evo = {m["name"]: [{"to": e["name"], "type": e["type"], "val": e.get("val"),
                        "item": e.get("item_name")} for e in m["evolutions"]]
           for m in monsters if m.get("evolutions")}
    with open(os.path.join(DATA, "evolutions.json"), "w", encoding="utf-8") as fh:
        json.dump(evo, fh, separators=(",", ":"), sort_keys=True)
    print(f"  {'evolutions.json':15} {len(evo):5} entries")

    # {species: [slot1, slot2, hidden-or-null]} - PokeMMO lists 3 ability slots,
    # the 3rd being the hidden ability (or a "--" placeholder when there is none).
    def _abils(mon):
        names = [a["name"] for a in mon.get("abilities", [])]
        names += [None] * (3 - len(names))
        hidden = names[2] if names[2] and names[2] not in ("--", "-") \
            and names[2] not in names[:2] else None
        return [names[0], names[1], hidden]
    abils = {m["name"]: _abils(m) for m in monsters}
    with open(os.path.join(DATA, "species_abilities.json"), "w", encoding="utf-8") as fh:
        json.dump(abils, fh, separators=(",", ":"), sort_keys=True)
    print(f"  {'species_abilities':15} {len(abils):5} entries")

    # {species: [egg-exclusive moves]} - a move only obtainable by breeding the
    # line (present as EGG on some stage, never as level/TM/tutor on any stage).
    prevo = {e["name"]: m["name"] for m in monsters for e in m.get("evolutions", [])}
    moves_by = {m["name"]: m.get("moves", []) for m in monsters}

    def _line(sp):
        chain = [sp]
        while chain[-1] in prevo and prevo[chain[-1]] not in chain:
            chain.append(prevo[chain[-1]])
        return chain

    egg_moves = {}
    for mon in monsters:
        egg, other = set(), set()
        for stage in _line(mon["name"]):
            for mv in moves_by.get(stage, []):
                (egg if "EGG" in mv["type"] else other).add(mv["name"])
        only = sorted(egg - other)
        if only:
            egg_moves[mon["name"]] = only
    with open(os.path.join(DATA, "egg_moves.json"), "w", encoding="utf-8") as fh:
        json.dump(egg_moves, fh, separators=(",", ":"), sort_keys=True)
    print(f"  {'egg_moves.json':15} {len(egg_moves):5} entries")


if __name__ == "__main__":
    print("building reference lists from", os.path.normpath(DUMP))
    main()
